# Auto-generated by .github/workflows/release-cli.yml on every cli/v* tag.
# Do not edit by hand — pushed to github.com/em-zom/homebrew-safenode.
class Safenode < Formula
  desc "Zero-knowledge CLI for the SafeNode credential vault"
  homepage "https://safenode.dev/cli"
  version "0.2.0"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/EM-Zom/homebrew-safenode/releases/download/cli/v#{version}/safenode-darwin-arm64.tar.gz"
      sha256 "1bfb0610167f81bb8ef170524db3613ea7e6e6035d157b104a6e2bb3baee0561"
    end
    on_intel do
      url "https://github.com/EM-Zom/homebrew-safenode/releases/download/cli/v#{version}/safenode-darwin-amd64.tar.gz"
      sha256 "127ced8f44a685d27e61698da5070d0dacadef5a62c415181b123cbd85652c4b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/EM-Zom/homebrew-safenode/releases/download/cli/v#{version}/safenode-linux-arm64.tar.gz"
      sha256 "beed77dd92120d0ce690feab45979c59fd7dd4866148f14c00e8183ce8ace177"
    end
    on_intel do
      url "https://github.com/EM-Zom/homebrew-safenode/releases/download/cli/v#{version}/safenode-linux-amd64.tar.gz"
      sha256 "937b8e1edeb287b982003ffdc8321a0c4b2a61b4a63ed651b21f3fdeb4a3fff8"
    end
  end

  def install
    arch_suffix = Hardware::CPU.arm? ? "arm64" : "amd64"
    os_suffix = OS.mac? ? "darwin" : "linux"
    bin.install "safenode-#{os_suffix}-#{arch_suffix}" => "safenode"
  end

  test do
    assert_match "safenode", shell_output("#{bin}/safenode --help 2>&1", 0..2)
  end
end
